src/Handler/CloudWatch.php
Protecting agains "PHP Notice:  Undefined index: uploadSequenceToken" in case one was not defined.
(*) For the record, it seem like this behavior happens only when connecting to an account for the first time.
Still, this should not happen.
=> Using stream uploadSequenceToken only if it was defined

src/Handler/CloudWatch.php
This addresses an issue where a cloned handler does not flush its
buffer.
=> Implement a clone method to register the handler's shutdown function.

src/Handler/CloudWatch.php
Hi @maxbanton,
we'd like to use `cwh` in a combination with `\Monolog\Handler\FingersCrossedHandler` but it seems these two handlers are incompatible.
I tried to describe the problem as much as possible.
Thank you for your time!
`close` methods of handlers are called in the wrong order:
```
1. Maxbanton\Cwh\Handler\CloudWatch::close // flushes its buffer to AWS service
2. Monolog\Handler\FingersCrossedHandler::close // flushes its buffer to Cloudwatch Handler
3. Maxbanton\Cwh\Handler\CloudWatch::__destruct // does not do anything intentionally
```
resulting in the buffer of `CloudWatchHandler` being filled by `FingersCrossedHandler` after `CloudWatchHandler` pushed data to AWS.
The `close` method of monolog handlers is called in `\Monolog\Handler\AbstractHandler::__destruct` but `close` …
=> Make cwh compatible with Monolog FingersCrossedHandler

.travis.yml
This PR
💁‍♂️ For reference, see https://docs.travis-ci.com/user/customizing-the-build#The-Build-Lifecycle.
=> Fix: Move build steps to appropriate sections in travis.yml

tests/Handler/CloudWatchTest.php
This PR
💁‍♂️ Since we require PHP5.6, this should be good. See [`composer.json`](https://github.com/maxbanton/cwh/blob/86b212a4ff1acb35653f4d5ac6299050b9d333b7/composer.json#L20).
=> Enhancement: Use short array syntax

tests/Handler/CloudWatchTest.php
=> Fix: Class name does not match file name

tests/Handler/CloudWatchTest.php
This PR
💁‍♂️ This is the visibility as declared on the parent; there's no need to modify it.
=> Fix: Reduce visibility

tests/Handler/CloudWatchTest.php
This PR
💁‍♂️ Since we require `phpunit/phpunit:^5.6.`, this should be good to go.
=> Fix: Extend from namespaced test case

.travis.yml, composer.json
This PR
💁‍♂️ Then we don't need to specify it when installing dependencies.
=> Enhancement: Configure preferred installation method in composer.json

src/Handler/CloudWatch.php
This PR
💁‍♂️ Running
```
$ phpstan analyse --level=max src
```
on current `master` yields
```
1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
------ --------------------------------------------------------------------------------------------------------------------
Line   src/Handler/CloudWatch.php
------ --------------------------------------------------------------------------------------------------------------------
194    PHPDoc tag @param has invalid value ($record): Unexpected token "$record", expected TOKEN_IDENTIFIER at offset 122
------ --------------------------------------------------------------------------------------------------------------------
[ERROR] Found 1 error
```
=> Fix: Add missing parameter type to docblock

phpunit.xml.dist
=> Enhancement: Reference phpunit.xsd in phpunit.xml

src/Handler/CloudWatch.php
Allows for you to pass null into the `$retention` parameter. This will not set a retention policy so your logs can be retained indefinitely.
If you pass null into the `$retention` parameter the log group is created, but the putRetentionPolicy call fails because `retentionInDays` must not be null according to the [documentation](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutRetentionPolicy.html). As a result the log stream is not created until initialize() is called a second time.
Optionally allows for you to have never expiring logs.
* …
=>  Add support for indefinite retention

src/Handler/CloudWatch.php
Fix/Feature: Adds handling of max event size of 256 KB https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html
Currently, if a large message (256 KB or larger) is being logged, there is a `Aws\CloudWatchLogs\Exception\CloudWatchLogsException` runtime exception thrown with a message similar to "Log event too large: 524256 bytes exceeds limit of 262144"}" which if unhandled breaks code execution.
With the new behavior the message is split into smaller chunks and logged as separate events. It does simply cut the string at the limit size.
* …
=> Fix: Support for max event size limit

src/Handler/CloudWatch.php
Bug fix
An exception about an invalid CloudWatch log stream sequence token appears while running a long script in Docker. I suspect another process creates a new sequence token and invalidates the one used by a Docker instance. This will probably happen when running a cluster of few web instances trying to write logs in a same time too.
Exception:
```
23:03:37 ERROR [console] Error thrown while running command "*****". 
Message: "Error executing "PutLogEvents" on "https://logs.eu-central-1.amazonaws.com"; 
AWS HTTP error: Client error: `POST https://logs.eu-central-1.amazonaws.com` resulted in a `400 Bad Request` response:
{ …
```
=> Refresh with fresh sequence token

src/Handler/CloudWatch.php
Bug fix
https://github.com/maxbanton/cwh/issues/61
Buffer will be flushed directly when a record is added AND batch size had been reached
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No, difficult to come up with a test though
=> Consider to flush buffer after a record has been processed

README.md
Also discussed (a bit) here: https://github.com/maxbanton/cwh/issues/27
Docs update
No mention of possibility to use the JsonFormatter
Encourage usage of the JsonFormater
* **Does this PR introduce a breaking change?** 
No
Using the JsonFormatter allows the user to use CloudWatch Log Insights as well to "query" the logs
https://aws.amazon.com/blogs/aws/new-amazon-cloudwatch-logs-insights-fast-interactive-log-analytics/
=> Suggest to assign the JsonFormatter in the documentation

src/Handler/CloudWatch.php, tests/Handler/CloudWatchTest.php
* **What kind of change does this PR introduce?**
Bug fix
* **What is the current behavior?**
If DescribeLogGroups throws an error (e.g. AccessDeniedException), the retry logic
will still call DescribeLogStreams, which will also fail, either with
AccessDeniedException, or, more confusingly, with "The specified log group
does not exist." if the log group has never been created.
This change makes sure that the original error is thrown.
* **Does this PR introduce a breaking change?**
Nope.
=> Do not overshadow errors thrown by DescribeLogGroups with those from DescribeLogStreams

src/Handler/CloudWatch.php, tests/Handler/CloudWatchTest.php
Bug fix
Create LineFormatter with the $ignoreEmptyContextAndExtra set to false
Create LineFormatter with the $ignoreEmptyContextAndExtra set to true 
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No
This fix losing [stacktrace] data.
This fix showing [] [] in cloudwatch console.
The attributes passed to LineFormatter are being suggested by AWS documentation. Please refer to https://aws.amazon.com/blogs/developer/php-application-logging-with-amazon-cloudwatch-logs-a …
=> Enhancement: Use AWS suggested LineFormatter attributes

src/Handler/CloudWatch.php, tests/Handler/CloudWatchTest.php
Bug fix.
* **What is the current behavior?**
See issues #32 and #69.
Chronological order of log entries is ensured before submission.
* **Does this PR introduce a breaking change?**
No.
The comparison logic is the fastest one still supported on PHP 5.6. The spaceship operator seems to be a little bit faster, but not available in PHP 5.
=> Sort log entries chronologically before calling PutLogEvents.

README.md, src/Handler/CloudWatch.php, tests/Handler/CloudWatchTest.php
feature
The handler checks for existence of the given log group, if it doesn't exist, it created the log group
By enabling the option, the handler doesn't check for the group's existence and goes on with initializing the stream.
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No, existing behavior remains unchanged. 
User has to explicitly trigger the option
This change was made in an effort to reduce the security boundaries of the application (I create the log …
=> Added option to disable creating the log group

README.md
Permissions for listing the existing log groups need to be able to list all the log groups on the account, to allow it to filter the groups based on the log group name.  If you don't, you end up not getting a log stream or any log data.
* **What kind of change does this PR introduce?** 
Docs update
* **What is the current behavior?**
With the default permissions, you can't list the log groups, resulting in you not getting any logs into CloudWatch Logs.
N/A
* **Does this PR introduce a breaking change?**
No. 
`
From my testing using the AWS CLI, I set up a user with the following permissions:
```
{
"Version": "2012-10-17",
"Statement": [
{
"Action": "logs:DescribeLogGroups",
"Resource": …
```
=> Updated the permission resources in the readme for DescribeLogGroups

phpunit.xml.dist, src/Handler/CloudWatch.php, tests/Handler/CloudWatchTest.php
This is a bug fix for https://github.com/maxbanton/cwh/issues/96, which occurs when calling PutLogEvents with records spanning more than 24 hours.
The AWS SDK throws a CloudWatchLogsException with the message:
> The batch of log events in a single PutLogEvents request cannot span more than 24 hours.
The CloudWatch handler will check whether a record's timestamp is more than 24 hours after the earliest timestamp, and if so calls PutLogEvents before adding the new record to the buffer.
* **Does this PR introduce a breaking change?** (What changes might users need to …
=> Flush the record buffer before the timespan of all records exceeds 24 hours
